import { Product } from "@/types/product";

const productsData: Product[] = [
  {
    id: 1,
    image: "/images/products/3d-rendering-wooden-house_1.jpg",
    title: "3d-rendering-wooden-house_1",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 2,
    image: "/images/products/3d-rendering-wooden-house_2.jpg",
    title: "3d-rendering-wooden-house_2",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 3,
    image: "/images/products/arafed-wooden-deck-with-couch-table-garden.jpg",
    title: "arafed-wooden-deck-with-couch-table-garden",
    content: "",
    oldprice: "50023",
    newprice: "50023",
  },
  {
    id: 4,
    image: "/images/products/luxurious-villa-with-modern-architectural-design_1.jpg",
    title: "luxurious-villa-with-modern-architectural-design_1",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 5,
    image: "/images/products/luxurious-villa-with-modern-architectural-design_2.jpg",
    title: "luxurious-villa-with-modern-architectural-design_2",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 6,
    image: "/images/products/luxurious-villa-with-modern-architectural-design_3.jpg",
    title: "luxurious-villa-with-modern-architectural-design_3",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 7,
    image: "/images/products/photorealistic-house-with-wooden-architecture-timber-structure.jpg",
    title: "photorealistic-house-with-wooden-architecture-timber-structure",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 8,
    image: "/images/products/photorealistic-wooden-house-with-timber-structure_1.jpg",
    title: "photorealistic-wooden-house-with-timber-structure_1",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 9,
    image: "/images/products/photorealistic-wooden-house-with-timber-structure_2.jpg",
    title: "photorealistic-wooden-house-with-timber-structure_2",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 10,
    image: "/images/products/photorealistic-wooden-house-with-timber-structure_3.jpg",
    title: "photorealistic-wooden-house-with-timber-structure_3",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 11,
    image: "/images/products/realistic-house-with-wooden-architecture-timber-structure.jpg",
    title: "realistic-house-with-wooden-architecture-timber-structure",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
  {
    id: 12,
    image: "/images/products/sustainable-tiny-house-community-minimal-impact.jpg",
    title: "sustainable-tiny-house-community-minimal-impact",
    content: "",
    oldprice: "500",
    newprice: "500",
  },
];
export default productsData;
