import { Menu } from "@/types/menu";

const menuData: Menu[] = [
  {
    id: 1,
    title: "Home",
    index: 0,
    path: "/",
    newTab: false,
  },
  {
    id: 2,
    title: "About",
    index: 1,
    path: "/about",
    newTab: false,
  },
  {
    id: 3,
    title: "Design Catalog",
    index: 2,
    path: "/blog",
    newTab: false,
    submenu: [
      {
        id: 31,
        title: "Architecture Design",
        index: 0,
        path: "/about",
        newTab: false,
        submenu: [
          {
            id: 311,
            title: "House",
            path: "/about",
            newTab: false,
          },
          {
            id: 312,
            title: "Villa",
            path: "/contact",
            newTab: false,
          },
          {
            id: 313,
            title: "Palace",
            path: "/blog",
            newTab: false,
          },
          {
            id: 314,
            title: "Comm./Resid.Towers",
            path: "/blog-sidebar",
            newTab: false,
          },
          {
            id: 315,
            title: "Residential Buildings",
            path: "/blog-details",
            newTab: false,
          },
          {
            id: 316,
            title: "Commercial Buildings",
            path: "/signin",
            newTab: false,
          },
          {
            id: 317,
            title: "Hotels",
            path: "/blog-details",
            newTab: false,
          },
          {
            id: 318,
            title: "Gym & SPA",
            path: "/signin",
            newTab: false,
          },
        ],
      },
      {
        id: 32,
        title: "Landscape Design",
        index: 1,
        path: "/contact",
        newTab: false,
        submenu: [
          {
            id: 321,
            title: "Parks",
            path: "/about",
            newTab: false,
          },
          {
            id: 322,
            title: "Streetscape",
            path: "/contact",
            newTab: false,
          },
        ],
      },
      {
        id: 33,
        title: "Industrial Design",
        index: 2,
        path: "/blog",
        newTab: false,
        submenu: [
          {
            id: 323,
            title: "Tiny Houses",
            path: "/about",
            newTab: false,
          },
          {
            id: 324,
            title: "Portable Houses",
            path: "/contact",
            newTab: false,
          },
          {
            id: 325,
            title: "RV / Camper",
            path: "/about",
            newTab: false,
          },
          {
            id: 326,
            title: "Tent",
            path: "/contact",
            newTab: false,
          },
          {
            id: 327,
            title: "Tiny Restaurant/Cafe",
            path: "/about",
            newTab: false,
          },
          {
            id: 328,
            title: "Portable Truck Food/Cafe",
            path: "/contact",
            newTab: false,
          },
          {
            id: 329,
            title: "Portable Ice Cream",
            path: "/about",
            newTab: false,
          },
          {
            id: 330,
            title: "Kiosks/Exhibition",
            path: "/contact",
            newTab: false,
          },
          {
            id: 331,
            title: "Furniture's",
            path: "/about",
            newTab: false,
          },
          {
            id: 332,
            title: "Lights",
            path: "/contact",
            newTab: false,
          },
          {
            id: 333,
            title: "Art/Decoration",
            path: "/about",
            newTab: false,
          },
        ],
      },
      {
        id: 34,
        title: "Marine Design",
        index: 3,
        path: "/blog-sidebar",
        newTab: false,
        submenu: [
          {
            id: 341,
            title: "Floating Houses",
            path: "/about",
            newTab: false,
          },
          {
            id: 342,
            title: "Floating Restaurant/Cafe",
            path: "/contact",
            newTab: false,
          },
          {
            id: 343,
            title: "Yacht/Boat",
            path: "/contact",
            newTab: false,
          },
        ],
      },
      {
        id: 35,
        title: "Products Design",
        index: 4,
        path: "/blog-details",
        newTab: false,
        submenu: [
          {
            id: 351,
            title: "Assemblies Toy's",
            path: "/about",
            newTab: false,
          },
        ],
      },
      {
        id: 36,
        title: "Prototype Design",
        index: 5,
        path: "/signin",
        newTab: false,
        submenu: [
          {
            id: 361,
            title: "Prototype Design",
            path: "/about",
            newTab: false,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Design Convert",
    index: 3,
    path: "/contact",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Conceptual Design",
        index: 0,
        path: "/about",
        newTab: false,
        submenu: [
          {
            id: 411,
            title: "Blueprints",
            path: "/about",
            newTab: false,
          },
          {
            id: 412,
            title: "3D Animations",
            path: "/about",
            newTab: false,
          },
        ],
      },
      {
        id: 42,
        title: "Blueprints",
        index: 1,
        path: "/about",
        newTab: false,
        submenu: [
          {
            id: 421,
            title: "3D Visualization",
            path: "/about",
            newTab: false,
          },
          {
            id: 422,
            title: "3D Animation",
            path: "/about",
            newTab: false,
          },
        ],
      },
      {
        id: 43,
        title: "Hand Sketch",
        index: 2,
        path: "/about",
        newTab: false,
        submenu: [
          {
            id: 431,
            title: "Conceptual Design",
            path: "/about",
            newTab: false,
          },
          {
            id: 432,
            title: "Blueprints",
            path: "/about",
            newTab: false,
          },
          {
            id: 433,
            title: "3D Animation",
            path: "/about",
            newTab: false,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Drawings Prepare",
    index: 4,
    newTab: false,
    submenu: [
      {
        id: 51,
        title: "Shop Drawing",
        path: "/about",
        newTab: false,
      },
      {
        id: 52,
        title: "Constructions Drawing",
        path: "/contact",
        newTab: false,
      },
      {
        id: 53,
        title: "Fabrication Drawing",
        path: "/blog",
        newTab: false,
      },
    ],
  },
  {
    id: 6,
    title: "Get Stamp",
    index: 5,
    path: "/contact",
    newTab: false,
  },
  {
    id: 7,
    title: "Contact",
    index: 6,
    path: "/contact",
    newTab: false,
  },
];
export default menuData;
